package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Test вакансии ведущего тестировщика")
    void generatedTest() {
        step("Open https://job.detmir.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("Перейти через левое меню в вакансии", () -> {
            step("// todo: just add selenium action");
        });

        step("Пагинация - нажать на кнопку \"показать больше\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что пришёл ответ 200", () -> {
            step("// todo: just add selenium action");
        });

        step("Выбрать метро - Окружная", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что пришёл ответ 200", () -> {
            step("// todo: just add selenium action");
        });

        step("Выбрать 3 страницу", () -> {
            step("// todo: just add selenium action");
        });

        step("Найти вакансию ведущего тестировщика", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что зп = 250", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить, что в требованиях есть Selenide", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://job.detmir.ru/'", () ->
            open("https://job.detmir.ru/"));

        step("Page title should have text 'Работа в детском мире -'", () -> {
            String expectedTitle = "Работа в детском мире -";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://job.detmir.ru/'", () ->
            open("https://job.detmir.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}